#!/bin/bash
set -e
cp 70-persistent-net.rules neuland/etc/udev/rules.d/
cp setupNetworking neuland/opt/net/
cp ifup@.service neuland/etc/systemd/system/
dpkg-deb --build neuland/
mv neuland.deb neuland-0.1_amd64.deb
